services:

  auth_service:
    build: ./auth_service
    expose:
      - 8080

  event_service:
    build: ./event_service
    expose:
      - 8081
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_db:/data/db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - auth_service
      - event_service

volumes:
  mongo_db:
